### ISSUE TITLE
Spaces replace the hyphen on package names

### ISSUE THREAD

**Issue by heavysixer** [yeoman/generator-gruntfile#25] opened 2015-02-27 18:50 UTC
Hi @addyosmani 
I noticed that when you have a project with hyphens the generated gruntfile replaces them with spaces. Consider the following:

```json
{
  "name": "appify-components",
  "version": "0.0.0",
  "dependencies": {},
  "devDependencies": {
    "grunt": "~0.4.2",
    "grunt-contrib-watch": "~0.5.3",
    "grunt-contrib-concat": "~0.3.0",
    "grunt-contrib-uglify": "~0.2.7",
    "grunt-contrib-jshint": "~0.7.2",
    "grunt-contrib-qunit": "*"
  }
}
```
```javascript
dist: {
                src: ['lib/appify components.js'],
                dest: 'dist/appify components.js'
            }
```

I am happy to work on a PR for this issue but wanted to make sure this was not done by design first.

**Comment by SBoudrias** [comment] 2015-02-27 19:14
This is not by design, fix welcome!

**Comment by heavysixer** [comment] 2015-03-02 15:09
@SBoudrias i know we went round and round on this on Friday, but am curious if everything is looking good now? Thanks again for all the help getting this PR in great shape.

**Comment by arthurvr** [comment] 2015-04-08 22:02
The PR was merged so this issue can be closed I guess?

**Comment by SBoudrias** [comment] 2015-04-08 22:05
:+1:

**Closed** 2015-04-08 22:05 UTC
